# Generated by Django 6.0.7 on 2026-09-25 12:46

import django.db.models.deletion
import filemanager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=filemanager.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
